### ISSUE TITLE
你好，方便优化代码，让它在pycharm等编辑上 的智能提示 更友好吗

### ISSUE THREAD

**Issue by shifenhutu** [ackness/many_abis#13]
你好， 我目前 是这样加载的 （多个 中括号  拼接）

编辑器没办法智能提示， 只能手动拼接， 

不知道 未来是否有计划完善智能提示 

谢谢

```python
from many_abis import ABIS, CHAINS
 
uniswap_factory_abi = ABIS["UNISWAP_V2_FACTORY"]
uniswap_factory_address = CHAINS["eth"]["dex"]["uniswap_v2"]["factory_address"]
```

**Comment by ackness** [comment]
你好，感谢你的建议
pycharm 等工具的智能提示不能获取动态加载的类内的变量名称， many_abis  为了方便后面添加多链的数据，在 0.1.0 的时候变成了从json配置中加载，如果需要增加智能提升功能可能需要更改大量的代码逻辑。
之后的版本会增加支持

**Comment by ackness** [comment]
现在已经支持了
